/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Artifact represents the output of the last successful repository sync.
 */
@ApiModel(description = "Artifact represents the output of the last successful repository sync.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-05T14:06:13.160Z[Etc/UTC]")
public class V1GitHubRepositoryStatusArtifact {
  public static final String SERIALIZED_NAME_REVISION = "revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  private String revision;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public V1GitHubRepositoryStatusArtifact revision(String revision) {
    
    this.revision = revision;
    return this;
  }

   /**
   * Revision is a human readable identifier traceable in the origin source system. It can be a Git commit SHA, Git tag, a Helm index timestamp, a Helm chart version, etc.
   * @return revision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Revision is a human readable identifier traceable in the origin source system. It can be a Git commit SHA, Git tag, a Helm index timestamp, a Helm chart version, etc.")

  public String getRevision() {
    return revision;
  }


  public void setRevision(String revision) {
    this.revision = revision;
  }


  public V1GitHubRepositoryStatusArtifact url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL is the HTTP address of this artifact.
   * @return url
  **/
  @ApiModelProperty(required = true, value = "URL is the HTTP address of this artifact.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GitHubRepositoryStatusArtifact v1GitHubRepositoryStatusArtifact = (V1GitHubRepositoryStatusArtifact) o;
    return Objects.equals(this.revision, v1GitHubRepositoryStatusArtifact.revision) &&
        Objects.equals(this.url, v1GitHubRepositoryStatusArtifact.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(revision, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GitHubRepositoryStatusArtifact {\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

