/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * GitHubRepositoryStatus defines the observed state of a Git repository.
 */
@ApiModel(description = "GitHubRepositoryStatus defines the observed state of a Git repository.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-05T14:06:13.160Z[Etc/UTC]")
public class V1GitHubRepositoryStatus {
  public static final String SERIALIZED_NAME_ARTIFACT = "artifact";
  @SerializedName(SERIALIZED_NAME_ARTIFACT)
  private V1GitHubRepositoryStatusArtifact artifact;

  public V1GitHubRepositoryStatus artifact(V1GitHubRepositoryStatusArtifact artifact) {
    
    this.artifact = artifact;
    return this;
  }

   /**
   * Get artifact
   * @return artifact
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GitHubRepositoryStatusArtifact getArtifact() {
    return artifact;
  }


  public void setArtifact(V1GitHubRepositoryStatusArtifact artifact) {
    this.artifact = artifact;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GitHubRepositoryStatus v1GitHubRepositoryStatus = (V1GitHubRepositoryStatus) o;
    return Objects.equals(this.artifact, v1GitHubRepositoryStatus.artifact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifact);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GitHubRepositoryStatus {\n");
    sb.append("    artifact: ").append(toIndentedString(artifact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

